modLoader = "javafml"
loaderVersion= "[36,)"
license = "MIT"

[[mods]]
modId = "recentrecipe"
version = "1.0"
displayName = "Recentrecipe"
displayURL= ""
issueTrackerURL = ""
logoFile = "RecentRecipeLogo.png"
credits =""
authors = "AreUThreateningMe"
description = '''
'''

[[dependencies.recentrecipe]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.recentrecipe]]
modId = "minecraft"
mandatory= true
versionRange = "[1.16.5]"
ordering = "AFTER"
side ="BOTH"
